# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_project',
                'doc_host': 'https://charmi1128.github.io',
                'git_url': 'https://github.com/charmi1128/nbdev_project',
                'lib_path': 'nbdev_project'},
  'syms': {}}
